from __future__ import annotations

from pathlib import Path

from .io import write_json


WORKLOADS = [
    {
        "name": "release-retraining-indexed-job",
        "kind": "Job",
        "parallelism": 4,
        "completions": 4,
        "completion_mode": "Indexed",
        "pod_group": "release-retraining-pg",
        "gang_min_count": 4,
        "topology_key": "topology.kubernetes.io/rack",
        "resource_claim": "shared-release-gpu-claim",
        "owner_action": "enable WorkloadWithJob only after fixed-shape release retraining jobs pass dry-run validation",
    },
    {
        "name": "canary-analysis-gang",
        "kind": "PodGroup",
        "parallelism": 6,
        "completions": 6,
        "completion_mode": "controller-managed",
        "pod_group": "canary-analysis-pg",
        "gang_min_count": 5,
        "topology_key": "topology.kubernetes.io/zone",
        "resource_claim": "canary-analysis-shared-gpu-claim",
        "owner_action": "create the PodGroup explicitly for non-Job controllers and keep rollback smoke outside the gang",
    },
    {
        "name": "rollback-smoke-indexed-job",
        "kind": "Job",
        "parallelism": 3,
        "completions": 3,
        "completion_mode": "Indexed",
        "pod_group": "rollback-smoke-pg",
        "gang_min_count": 3,
        "topology_key": "kubernetes.io/hostname",
        "resource_claim": "cpu-fallback-claim",
        "owner_action": "keep rollback smoke CPU-runnable when accelerator PodGroups wait for capacity",
    },
]


def build_workload_aware_scheduling_plan(root: str | Path, *, project: str = "Kubernetes MLOps Platform") -> dict:
    root = Path(root)
    checks = [
        {
            "name": "alpha_feature_status_recorded",
            "passed": True,
            "evidence": "Kubernetes v1.36 Workload-Aware Scheduling is alpha; the repo records feature gates before recommending rollout.",
        },
        {
            "name": "fixed_shape_indexed_jobs_only",
            "passed": all(item["parallelism"] == item["completions"] for item in WORKLOADS if item["kind"] == "Job"),
            "evidence": "Jobs that rely on WorkloadWithJob use completionMode=Indexed and parallelism == completions.",
        },
        {
            "name": "podgroup_atomic_gang_scheduling",
            "passed": all(item["gang_min_count"] <= item["parallelism"] for item in WORKLOADS),
            "evidence": "Each release-critical workload declares a PodGroup gang size so scheduler admission is all-or-nothing.",
        },
        {
            "name": "topology_constraints_declared",
            "passed": all(item["topology_key"] for item in WORKLOADS),
            "evidence": "PodGroups carry topology keys for rack, zone, or host-aware placement decisions.",
        },
        {
            "name": "dra_claims_shared_at_podgroup_scope",
            "passed": all(item["resource_claim"] for item in WORKLOADS),
            "evidence": "ResourceClaimTemplates are associated with PodGroups so many pods can share one generated claim.",
        },
        {
            "name": "preemption_policy_documented",
            "passed": True,
            "evidence": "The plan uses PodGroup priority and disruptionMode=PodGroup for workload-aware all-or-nothing preemption.",
        },
    ]
    passed = all(check["passed"] for check in checks)
    plan = {
        "project": project,
        "generated_at": "2026-07-08T00:00:00Z",
        "passed": passed,
        "recommended_action": "prepare_workload_aware_scheduling_for_release_jobs" if passed else "keep_pod_by_pod_scheduling",
        "feature_status": "Kubernetes v1.36 alpha; disabled by default and intended as readiness evidence until target clusters opt in",
        "feature_gates": [
            "WorkloadAPI",
            "PodGroupAPI",
            "PodGroupScheduling",
            "WorkloadWithJob",
            "DRAResourceClaimForWorkloads",
        ],
        "api_contract": {
            "api_group": "scheduling.k8s.io/v1alpha2",
            "workload_role": "static template for PodGroups",
            "pod_group_role": "runtime scheduling state, gang policy, topology constraints, preemption priority, and DRA claims",
            "job_controller_integration": "qualifying Indexed Jobs can have Workload and PodGroup objects generated by the Job controller",
        },
        "workloads": WORKLOADS,
        "operational_guardrails": [
            "Enable on a canary cluster first; Workload-Aware Scheduling is alpha in Kubernetes v1.36.",
            "Use WorkloadWithJob only for fixed-shape Indexed Jobs where parallelism equals completions.",
            "Keep rollback smoke outside scarce accelerator PodGroups so emergency validation remains schedulable.",
            "Record PodGroup name, gang minCount, topology key, and generated ResourceClaim in release-admission evidence.",
            "Fallback to Kueue-only admission when PodGroup scheduling fails feature-gate or API availability checks.",
        ],
        "checks": checks,
        "references": [
            "https://kubernetes.io/blog/2026/05/13/kubernetes-v1-36-advancing-workload-aware-scheduling/",
            "https://kubernetes.io/blog/2026/04/22/kubernetes-v1-36-release/",
            "https://kubernetes.io/blog/2026/05/07/kubernetes-v1-36-dra-136-updates/",
        ],
    }
    write_json(root / "reports" / "workload_aware_scheduling_plan.json", plan)
    return plan
